
const zeroPadding = (n: number, digit: number): string => {
  if(0 <= n){
    return n.toString().padStart(digit, '0')
  }else{
    return '-' + Math.abs(n).toString().padStart(digit, '0')
  }
}

const skipNonExistentDate = (date: RubyDate): RubyDate => {
  const time = date.toDate().getTime()
  const timeOf1582_10_05 = -12220156800000
  const timeOf1582_10_14 = -12219379200000
  if(timeOf1582_10_05 <= time && time <= timeOf1582_10_14){
    return new RubyDate(1582, 10, 4)
  }
  return date
}

const JD_1582_10_04 = 2299160
const JD_1582_10_15 = 2299161

export default class RubyDate{

  private _d: Date

  constructor(year: number = -4712, month: number = 1, day: number = 1){
    const date = new Date(2000, 0, 1, 0, 0, 0, 0)
    date.setFullYear(year)
    date.setMonth(month - 1)
    date.setDate(day)
    if(isNaN(date.getTime())){
      throw new TypeError('Invalid Date')
    }
    this._d = date
  }

  static parse(str: string): RubyDate | null{
    if(typeof str !== 'string'){
      return null
    }
    // avoid UTC minus N hours timezone problem
    if(str.match(/^\d{4}-\d{2}-\d{2}$/)){
      str = str.replace(/-/g, '/')
    }
    const time = Date.parse(str)
    if(isNaN(time)){
      return null
    }
    const date = new Date(time)
    const year = date.getFullYear()
    const month = date.getMonth() + 1
    const day = date.getDate()
    return new RubyDate(year, month, day)
  }

  static today(): RubyDate{
    const now = new Date(Date.now())
    const year = now.getFullYear()
    const month = now.getMonth() + 1
    const day = now.getDate()
    return new RubyDate(year, month, day)
  }

  beginningOfMonth(): RubyDate{
    return new RubyDate(this.year(), this.month(), 1)
  }

  beginningOfYear(): RubyDate{
    return new RubyDate(this.year(), 1, 1)
  }

  day(): number{
    return this._d.getDate()
  }

  endOfMonth(): RubyDate{
    return new RubyDate(this.year(), this.month() + 1, 0)
  }

  endOfYear(): RubyDate{
    return new RubyDate(this.year(), 12, 31)
  }

  month(): number{
    return this._d.getMonth() + 1
  }

  nextDay(n: number = 1): RubyDate{
    const jd = this.jd()
    const julianGregorianBetweenDays = 10
    if(jd <= JD_1582_10_04 && JD_1582_10_04 < jd + n){
      return new RubyDate(this.year(), this.month(), this.day() + n + julianGregorianBetweenDays)
    }
    if(JD_1582_10_15 <= jd && jd + n < JD_1582_10_15){
      return new RubyDate(this.year(), this.month(), this.day() + n - julianGregorianBetweenDays)
    }
    return new RubyDate(this.year(), this.month(), this.day() + n)
  }

  nextMonth(n: number = 1): RubyDate{
    const year = this.year()
    const month = this.month()
    const day = this.day()
    const d1 = new RubyDate(year, month + n, day)
    const d2 = new RubyDate(year, month + n + 1, 0)
    return skipNonExistentDate(d1 < d2 ? d1 : d2)
  }

  nextYear(n: number = 1): RubyDate{
    const year = this.year()
    const month = this.month()
    const day = this.day()
    const d1 = new RubyDate(year + n, month, day)
    const d2 = new RubyDate(year + n, month + 1, 0)
    return skipNonExistentDate(d1 < d2 ? d1 : d2)
  }

  strftime(format: string): string{
    return format.replace(/%-?[aAdmYy%]/g, (substring: string): string => {
      if(substring.endsWith('-Y')){
        return this.year().toString()
      }
      if(substring.endsWith('Y')){
        return zeroPadding(this.year(), 4)
      }
      if(substring.endsWith('-y')){
        return (this.year() % 100).toString()
      }
      if(substring.endsWith('y')){
        return zeroPadding(this.year() % 100, 2)
      }
      if(substring.endsWith('-m')){
        return this.month().toString()
      }
      if(substring.endsWith('m')){
        return zeroPadding(this.month(), 2)
      }
      if(substring.endsWith('-d')){
        return this.day().toString()
      }
      if(substring.endsWith('d')){
        return zeroPadding(this.day(), 2)
      }
      if(substring.endsWith('a')){
        return [
          'Sun',
          'Mon',
          'Tue',
          'Wed',
          'Thu',
          'Fri',
          'Sat',
          'Sun',
        ][this.wday()]
      }
      if(substring.endsWith('A')){
        return [
          'Sunday',
          'Monday',
          'Tuesday',
          'Wednesday',
          'Thursday',
          'Friday',
          'Saturday',
          'Sunday',
        ][this.wday()]
      }
      if(substring.endsWith('%')){
        return '%'
      }
      return substring
    })
  }

  toDate(): Date{
    return new Date(this._d)
  }

  toString(): string{
    return `${zeroPadding(this.year(), 4)}-${zeroPadding(this.month(), 2)}-${zeroPadding(this.day(), 2)}`
  }

  valueOf(): number{
    return this.jd()
  }

  wday(): number{
    return this._d.getDay()
  }

  year(): number{
    return this._d.getFullYear()
  }

  // Generated by codex
  jd(): number{
    const year = this.year()
    const month = this.month()
    const day = this.day()
    const millisecondsPerDay = 86_400_000

    // Date.UTC treats years from 0 to 99 as 1900 to 1999,
    // so use setUTCFullYear instead.
    const utcDate = new Date(0)
    utcDate.setUTCHours(0, 0, 0, 0)
    utcDate.setUTCFullYear(year, month - 1, day)

    // JavaScript Date uses the proleptic Gregorian calendar.
    const gregorianJd = (
      Math.floor(utcDate.getTime() / millisecondsPerDay) +
      2440588
    )

    const isGregorian = (
      year > 1582 ||
      (year === 1582 && (month > 10 || (month === 10 && day >= 15)))
    )

    if(isGregorian){
      return gregorianJd
    }

    // The difference between the Julian and proleptic Gregorian
    // calendars changes over time.
    const adjustedYear = month <= 2 ? year - 1 : year
    const calendarDifference = (
      Math.floor(adjustedYear / 100) -
      Math.floor(adjustedYear / 400) -
      2
    )

    return gregorianJd + calendarDifference
  }

}
